blueprint:
  name: State change notifier
  description: Send a notification to a device when a state changes
  domain: automation
  source_url: https://github.com/wolffshots/hass_blueprints/blob/main/notify_on_state_change.yaml
  author: wolffshots
  input:
    state_entity:
      name: State entity
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
          
trigger:
  platform: state
  entity_id: !input state_entity
      
condition: []

action:
  - domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: "{{ state_attr(trigger.entity_id, 'friendly_name') }} changed"      
    message: >-
        State changed from {{ trigger.from_state.state }}{{
        trigger.from_state.attributes.unit_of_measurement }} to {{
        trigger.to_state.state }}{{
        trigger.from_state.attributes.unit_of_measurement }}
